# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reactn
email: hello@reactn.com
phone: +44 (0) 191 640 4631
description: > # this means to ignore newlines until "baseurl:"
  Reactn is a powerful customer feedback platform revolutionising the way organisations collect, distribute and act on customer insight and opinion.
baseurl: "" # the subpath of your site, e.g. /blog
author: Minestor
footer_notice: Minestor 2016
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ReactnUK

# Build settings
markdown: kramdown
